// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: cpegroup.proto

package conversion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CpeGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StormReadyFw bool `protobuf:"varint,1,opt,name=storm_ready_fw,json=stormReadyFw,proto3" json:"storm_ready_fw,omitempty"`
	Wanfailover  bool `protobuf:"varint,2,opt,name=wanfailover,proto3" json:"wanfailover,omitempty"`
	Gwfailover   bool `protobuf:"varint,3,opt,name=gwfailover,proto3" json:"gwfailover,omitempty"`
}

func (x *CpeGroup) Reset() {
	*x = CpeGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cpegroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CpeGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CpeGroup) ProtoMessage() {}

func (x *CpeGroup) ProtoReflect() protoreflect.Message {
	mi := &file_cpegroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CpeGroup.ProtoReflect.Descriptor instead.
func (*CpeGroup) Descriptor() ([]byte, []int) {
	return file_cpegroup_proto_rawDescGZIP(), []int{0}
}

func (x *CpeGroup) GetStormReadyFw() bool {
	if x != nil {
		return x.StormReadyFw
	}
	return false
}

func (x *CpeGroup) GetWanfailover() bool {
	if x != nil {
		return x.Wanfailover
	}
	return false
}

func (x *CpeGroup) GetGwfailover() bool {
	if x != nil {
		return x.Gwfailover
	}
	return false
}

var File_cpegroup_proto protoreflect.FileDescriptor

var file_cpegroup_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x70, 0x65, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0e, 0x78, 0x70, 0x63, 0x2e, 0x78, 0x64, 0x61, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x22, 0x72, 0x0a, 0x08, 0x43, 0x70, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x0a, 0x0e,
	0x73, 0x74, 0x6f, 0x72, 0x6d, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x79, 0x5f, 0x66, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x46, 0x77, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x61, 0x6e, 0x66, 0x61, 0x69, 0x6c, 0x6f, 0x76, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x61, 0x6e, 0x66, 0x61, 0x69, 0x6c,
	0x6f, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x77, 0x66, 0x61, 0x69, 0x6c, 0x6f, 0x76,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x67, 0x77, 0x66, 0x61, 0x69, 0x6c,
	0x6f, 0x76, 0x65, 0x72, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cpegroup_proto_rawDescOnce sync.Once
	file_cpegroup_proto_rawDescData = file_cpegroup_proto_rawDesc
)

func file_cpegroup_proto_rawDescGZIP() []byte {
	file_cpegroup_proto_rawDescOnce.Do(func() {
		file_cpegroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_cpegroup_proto_rawDescData)
	})
	return file_cpegroup_proto_rawDescData
}

var file_cpegroup_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cpegroup_proto_goTypes = []interface{}{
	(*CpeGroup)(nil), // 0: xpc.xdas.model.CpeGroup
}
var file_cpegroup_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cpegroup_proto_init() }
func file_cpegroup_proto_init() {
	if File_cpegroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cpegroup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CpeGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cpegroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cpegroup_proto_goTypes,
		DependencyIndexes: file_cpegroup_proto_depIdxs,
		MessageInfos:      file_cpegroup_proto_msgTypes,
	}.Build()
	File_cpegroup_proto = out.File
	file_cpegroup_proto_rawDesc = nil
	file_cpegroup_proto_goTypes = nil
	file_cpegroup_proto_depIdxs = nil
}