// generic message for keyspaces that uses Redis Hashes

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: hashes.proto

package conversion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XdasHashes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields map[string]string `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *XdasHashes) Reset() {
	*x = XdasHashes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hashes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XdasHashes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XdasHashes) ProtoMessage() {}

func (x *XdasHashes) ProtoReflect() protoreflect.Message {
	mi := &file_hashes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XdasHashes.ProtoReflect.Descriptor instead.
func (*XdasHashes) Descriptor() ([]byte, []int) {
	return file_hashes_proto_rawDescGZIP(), []int{0}
}

func (x *XdasHashes) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_hashes_proto protoreflect.FileDescriptor

var file_hashes_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x78, 0x70, 0x63, 0x2e, 0x78, 0x64, 0x61, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x87,
	0x01, 0x0a, 0x0a, 0x58, 0x64, 0x61, 0x73, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x12, 0x3e, 0x0a,
	0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x78, 0x70, 0x63, 0x2e, 0x78, 0x64, 0x61, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x58,
	0x64, 0x61, 0x73, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x1a, 0x39, 0x0a,
	0x0b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x63, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hashes_proto_rawDescOnce sync.Once
	file_hashes_proto_rawDescData = file_hashes_proto_rawDesc
)

func file_hashes_proto_rawDescGZIP() []byte {
	file_hashes_proto_rawDescOnce.Do(func() {
		file_hashes_proto_rawDescData = protoimpl.X.CompressGZIP(file_hashes_proto_rawDescData)
	})
	return file_hashes_proto_rawDescData
}

var file_hashes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hashes_proto_goTypes = []interface{}{
	(*XdasHashes)(nil), // 0: xpc.xdas.model.XdasHashes
	nil,                // 1: xpc.xdas.model.XdasHashes.FieldsEntry
}
var file_hashes_proto_depIdxs = []int32{
	1, // 0: xpc.xdas.model.XdasHashes.fields:type_name -> xpc.xdas.model.XdasHashes.FieldsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hashes_proto_init() }
func file_hashes_proto_init() {
	if File_hashes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hashes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XdasHashes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hashes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hashes_proto_goTypes,
		DependencyIndexes: file_hashes_proto_depIdxs,
		MessageInfos:      file_hashes_proto_msgTypes,
	}.Build()
	File_hashes_proto = out.File
	file_hashes_proto_rawDesc = nil
	file_hashes_proto_goTypes = nil
	file_hashes_proto_depIdxs = nil
}