// keyspace xac

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: xboaccount.proto

package conversion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XBOAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XBOAccount) Reset() {
	*x = XBOAccount{}
	mi := &file_xboaccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XBOAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XBOAccount) ProtoMessage() {}

func (x *XBOAccount) ProtoReflect() protoreflect.Message {
	mi := &file_xboaccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XBOAccount.ProtoReflect.Descriptor instead.
func (*XBOAccount) Descriptor() ([]byte, []int) {
	return file_xboaccount_proto_rawDescGZIP(), []int{0}
}

func (x *XBOAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *XBOAccount) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

var File_xboaccount_proto protoreflect.FileDescriptor

const file_xboaccount_proto_rawDesc = "" +
	"\n" +
	"\x10xboaccount.proto\x12\x0expc.xdas.model\"N\n" +
	"\n" +
	"XBOAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountTypeB\x0eZ\f.;conversionb\x06proto3"

var (
	file_xboaccount_proto_rawDescOnce sync.Once
	file_xboaccount_proto_rawDescData []byte
)

func file_xboaccount_proto_rawDescGZIP() []byte {
	file_xboaccount_proto_rawDescOnce.Do(func() {
		file_xboaccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xboaccount_proto_rawDesc), len(file_xboaccount_proto_rawDesc)))
	})
	return file_xboaccount_proto_rawDescData
}

var file_xboaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_xboaccount_proto_goTypes = []any{
	(*XBOAccount)(nil), // 0: xpc.xdas.model.XBOAccount
}
var file_xboaccount_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xboaccount_proto_init() }
func file_xboaccount_proto_init() {
	if File_xboaccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xboaccount_proto_rawDesc), len(file_xboaccount_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xboaccount_proto_goTypes,
		DependencyIndexes: file_xboaccount_proto_depIdxs,
		MessageInfos:      file_xboaccount_proto_msgTypes,
	}.Build()
	File_xboaccount_proto = out.File
	file_xboaccount_proto_goTypes = nil
	file_xboaccount_proto_depIdxs = nil
}
